# Admin controllers.
services:
    Vx\Sendifico\Controller\Admin\ConfigurationController:
        public: true
        autowire: true
        autoconfigure: true
        tags:
            - { name: controller.service_arguments }
