# Shared services loaded by admin and front kernels.
imports:
    - { resource: "components/repository/*.yml" }
    - { resource: "components/package/*.yml" }
    - { resource: "components/order/*.yml" }
