vx_sendifico_configuration:
    path: /vx-sendifico/configuration
    methods: [GET, POST]
    defaults:
        _controller: 'Vx\Sendifico\Controller\Admin\ConfigurationController::index'
        _legacy_controller: AdminVxSendificoConfiguration
        _legacy_link: AdminVxSendificoConfiguration
